/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;

import static PayRoll.UpdateEmp.isContactValid;
import static PayRoll.UpdateEmp.isEmailValid;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher; 
import java.util.regex.Pattern;

/**
 *
 * @author Vedant
 */
public class Add_Admin extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Add_Admin
     */
    public Add_Admin() {
        initComponents();
        con = con_class.java_con();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        lbl_emp.setText(String.valueOf(Emp.empID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        txt_cont = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        rd_male = new javax.swing.JRadioButton();
        rd_female = new javax.swing.JRadioButton();
        txt_fname = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clear_but = new javax.swing.JButton();
        save_but = new javax.swing.JButton();
        logout_but = new javax.swing.JButton();
        back_but = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        dp_doj = new javax.swing.JTextField();
        dp_dob = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Admin ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 70, 74, 27);

        txt_lname.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(txt_lname);
        txt_lname.setBounds(420, 120, 140, 30);

        txt_cont.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(txt_cont);
        txt_cont.setBounds(200, 310, 140, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hire Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 260, 81, 27);

        txt_email.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });
        getContentPane().add(txt_email);
        txt_email.setBounds(420, 310, 140, 30);

        rd_male.setBackground(new java.awt.Color(30, 99, 120));
        rd_male.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        rd_male.setForeground(new java.awt.Color(204, 204, 255));
        rd_male.setText("Male");
        rd_male.setContentAreaFilled(false);
        rd_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_maleActionPerformed(evt);
            }
        });
        getContentPane().add(rd_male);
        rd_male.setBounds(200, 170, 70, 23);

        rd_female.setBackground(new java.awt.Color(0, 75, 97));
        rd_female.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        rd_female.setForeground(new java.awt.Color(204, 204, 255));
        rd_female.setText("Female");
        rd_female.setContentAreaFilled(false);
        getContentPane().add(rd_female);
        rd_female.setBounds(270, 170, 80, 23);

        txt_fname.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(txt_fname);
        txt_fname.setBounds(200, 120, 140, 30);

        txt_id.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(txt_id);
        txt_id.setBounds(200, 70, 140, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 310, 81, 27);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 120, 83, 27);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 120, 81, 27);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Of Birth");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 210, 81, 27);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 170, 81, 27);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 310, 72, 27);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Admin Entry Form");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 10, 220, 29);

        clear_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        clear_but.setForeground(new java.awt.Color(0, 152, 153));
        clear_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear.png"))); // NOI18N
        clear_but.setText("Clear");
        clear_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_butActionPerformed(evt);
            }
        });
        getContentPane().add(clear_but);
        clear_but.setBounds(620, 210, 100, 39);

        save_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        save_but.setForeground(new java.awt.Color(0, 152, 153));
        save_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        save_but.setText("Save");
        save_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_butActionPerformed(evt);
            }
        });
        getContentPane().add(save_but);
        save_but.setBounds(620, 160, 100, 39);

        logout_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        logout_but.setForeground(new java.awt.Color(0, 152, 153));
        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logout_but.setFocusTraversalPolicyProvider(true);
        logout_but.setHideActionText(true);
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        getContentPane().add(logout_but);
        logout_but.setBounds(740, 0, 50, 40);

        back_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        back_but.setForeground(new java.awt.Color(0, 152, 153));
        back_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        back_but.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_butActionPerformed(evt);
            }
        });
        getContentPane().add(back_but);
        back_but.setBounds(680, 0, 50, 40);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logged in as : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 100, 27);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(120, 0, 66, 27);

        dp_doj.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(dp_doj);
        dp_doj.setBounds(200, 260, 140, 30);

        dp_dob.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(dp_dob);
        dp_dob.setBounds(200, 210, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 50, 770, 10);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        jLabel2.setFocusCycleRoot(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(810, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rd_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_maleActionPerformed

   
    public static boolean isEmailValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public static boolean isContactValid(String s) 
    { 
        // The given argument to compile() method  
        // is regular expression. With the help of  
        // regular expression we can validate mobile 
        // number.  
        // 1) Begins with 0 or 91 
        // 2) Then contains 7 or 8 or 9. 
        // 3) Then contains 9 digits 
        Pattern p = Pattern.compile("(0/91)?[7-9][0-9]{9}"); 
  
        // Pattern class contains matcher() method 
        // to find matching between given number  
        // and regular expression 
        Matcher m = p.matcher(s); 
        return (m.find() && m.group().equals(s)); 
    } 
    
    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
        LogIn x = new LogIn();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_butActionPerformed

    private void back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_butActionPerformed
        // TODO add your handling code here:
        MenuAdmin mm = new MenuAdmin();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_butActionPerformed

    private void save_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_butActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();
        String fname=txt_fname.getText();
        String lname = txt_lname.getText();
        String email = txt_email.getText();
        String mobile = txt_cont.getText();
        String gender = null;                      
        if(rd_male.isSelected())
            gender="Male";
        if(rd_female.isSelected())
            gender="Female";
        String dob = dp_dob.getText();
        String doj = dp_doj.getText();
        if((!isEmailValid(email))||(!isContactValid(mobile))){
              
               if(!isContactValid(mobile)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Contact Number!");
                   txt_cont.setText("");
               }
               if(!isEmailValid(email)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Email Address!");
                   txt_email.setText("");
               }
        }else{
            try {
                pst = con.prepareStatement("insert into administration(Admin_ID,First_Name,Last_Name,Email,Contact,Gender,DateOfBirth,DateOfJoining) values(?,?,?,?,?,?,?,?)");
                pst.setString(1, id);
                pst.setString(2, fname);
                pst.setString(3, lname);
                pst.setString(4, email);
                pst.setString(5, mobile);
                pst.setString(6, gender);
                pst.setString(7, dob);
                pst.setString(8, doj);
                pst.execute();
                JOptionPane.showMessageDialog(null,"New Admin Record Inserted Successfully");
                txt_id.setText("");
                txt_fname.setText("");
                txt_lname.setText("");
                dp_dob.setText("");
                txt_email.setText("");
                txt_cont.setText("");
                dp_doj.setText("");
            }
            catch (SQLException ex) {
                Logger.getLogger(Add_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }              
    }//GEN-LAST:event_save_butActionPerformed

    private void clear_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_butActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_fname.setText("");
        txt_lname.setText("");
        dp_doj.setText("");
        txt_email.setText("");
        txt_cont.setText("");
        dp_dob.setText("");
    }//GEN-LAST:event_clear_butActionPerformed

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_emailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Add_Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_but;
    private javax.swing.JButton clear_but;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField dp_dob;
    private javax.swing.JTextField dp_doj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JButton logout_but;
    private javax.swing.JRadioButton rd_female;
    private javax.swing.JRadioButton rd_male;
    private javax.swing.JButton save_but;
    private javax.swing.JTextField txt_cont;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lname;
    // End of variables declaration//GEN-END:variables
}
