/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vedant
 */
public class deduction extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form deduction
     */
    public deduction() {
        initComponents();
         con=con_class.java_con();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        lbl_emp.setText(String.valueOf(Emp.empID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_percentage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_deduction = new javax.swing.JTextField();
        r_percentage = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        r_amount = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_sal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        save_but = new javax.swing.JButton();
        calc_but = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_reason = new javax.swing.JTextField();
        clear_but = new javax.swing.JButton();
        search_but = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();
        logout_but = new javax.swing.JButton();
        txt_sal = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JLabel();
        txt_surname = new javax.swing.JLabel();
        txt_dob = new javax.swing.JLabel();
        txt_desig = new javax.swing.JLabel();
        txt_grade = new javax.swing.JLabel();
        txt_doj = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Hired");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 220, 70, 30);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Basic Salary");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 270, 70, 30);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the Employee ID\n to be searched:"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 250, 30);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Update Salary By");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 310, 100, 34);

        txt_search.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(280, 70, 330, 28);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Percentage");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 360, 100, 24);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 122, 88, 26);

        txt_percentage.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_percentageActionPerformed(evt);
            }
        });
        getContentPane().add(txt_percentage);
        txt_percentage.setBounds(110, 360, 170, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 88, 30);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amount");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 410, 82, 24);

        txt_deduction.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deductionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_deduction);
        txt_deduction.setBounds(110, 410, 170, 30);

        r_percentage.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        r_percentage.setForeground(new java.awt.Color(255, 255, 255));
        r_percentage.setText("Percentage");
        r_percentage.setContentAreaFilled(false);
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });
        getContentPane().add(r_percentage);
        r_percentage.setBounds(110, 310, 90, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Surname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 88, 30);

        r_amount.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        r_amount.setForeground(new java.awt.Color(255, 255, 255));
        r_amount.setText("Amount");
        r_amount.setContentAreaFilled(false);
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });
        getContentPane().add(r_amount);
        r_amount.setBounds(200, 310, 70, 30);

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Deduction");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(320, 356, 128, 40);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 270, 88, 30);

        lbl_total.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setText("0.00");
        getContentPane().add(lbl_total);
        lbl_total.setBounds(510, 360, 70, 40);

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Salary After Deduction");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(320, 410, 172, 30);

        lbl_sal.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        lbl_sal.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sal.setText("0.00");
        getContentPane().add(lbl_sal);
        lbl_sal.setBounds(510, 410, 60, 30);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Designation");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 120, 90, 26);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Grade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 170, 60, 30);

        save_but.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        save_but.setForeground(new java.awt.Color(0, 153, 152));
        save_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        save_but.setText("Save");
        save_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_butActionPerformed(evt);
            }
        });
        getContentPane().add(save_but);
        save_but.setBounds(690, 330, 130, 40);

        calc_but.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        calc_but.setForeground(new java.awt.Color(0, 153, 152));
        calc_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculate.png"))); // NOI18N
        calc_but.setText("Calculate");
        calc_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_butActionPerformed(evt);
            }
        });
        getContentPane().add(calc_but);
        calc_but.setBounds(690, 390, 130, 40);

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Reason");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 460, 85, 26);

        txt_reason.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        getContentPane().add(txt_reason);
        txt_reason.setBounds(110, 460, 500, 30);

        clear_but.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        clear_but.setForeground(new java.awt.Color(0, 153, 152));
        clear_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear.png"))); // NOI18N
        clear_but.setText("Clear");
        clear_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_butActionPerformed(evt);
            }
        });
        getContentPane().add(clear_but);
        clear_but.setBounds(690, 450, 130, 40);

        search_but.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        search_but.setForeground(new java.awt.Color(0, 153, 152));
        search_but.setText("Search");
        search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butActionPerformed(evt);
            }
        });
        getContentPane().add(search_but);
        search_but.setBounds(620, 70, 80, 30);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logged in as : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 93, 30);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(120, 0, 60, 30);

        BackBut.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 153, 152));
        BackBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut);
        BackBut.setBounds(650, 0, 50, 40);

        logout_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        logout_but.setForeground(new java.awt.Color(0, 152, 153));
        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logout_but.setFocusTraversalPolicyProvider(true);
        logout_but.setHideActionText(true);
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        getContentPane().add(logout_but);
        logout_but.setBounds(710, 0, 50, 40);

        txt_sal.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_sal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_sal);
        txt_sal.setBounds(440, 270, 170, 30);

        txt_id.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_id);
        txt_id.setBounds(110, 120, 170, 30);

        txt_firstname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(110, 170, 170, 30);

        txt_surname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_surname);
        txt_surname.setBounds(110, 220, 170, 30);

        txt_dob.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_dob);
        txt_dob.setBounds(110, 270, 170, 30);

        txt_desig.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_desig.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_desig);
        txt_desig.setBounds(440, 120, 170, 30);

        txt_grade.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_grade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_grade);
        txt_grade.setBounds(440, 170, 170, 30);

        txt_doj.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_doj.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_doj);
        txt_doj.setBounds(440, 220, 170, 30);

        background.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 770);

        setSize(new java.awt.Dimension(880, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deductionActionPerformed

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
        r_percentage.setSelected(true);
        r_amount.setSelected(false);
        //r_amount.setEnabled(false);
        txt_deduction.setEnabled(false);
        txt_percentage.setEditable(true);
        txt_percentage.setEnabled(true);
        txt_deduction.setText("");
    }//GEN-LAST:event_r_percentageActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:
        r_amount.setSelected(true);
        r_percentage.setSelected(false);
        //r_percentage.setEnabled(false);
        txt_percentage.setEnabled(false);
        txt_deduction.setEditable(true);
        txt_deduction.setEnabled(true);
        txt_percentage.setText("");
    }//GEN-LAST:event_r_amountActionPerformed

    private void save_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_butActionPerformed
        // TODO add your handling code here:
        String value3 = lbl_emp.getText();
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update the salary record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try {
                String sql ="insert into deductions(Employee_ID,First_Name,Last_Name,Salary,Deduction_Amount,Deduction_Reason,MadeBy) values (?,?,?,?,?,?,?)";
                pst=con.prepareStatement(sql);
                pst.setString(1,txt_id.getText());
                pst.setString(2,txt_firstname.getText());   
                pst.setString(3,txt_surname.getText());
                pst.setString(4,txt_sal.getText());
                pst.setString(5,lbl_total.getText());
                pst.setString(6,txt_reason.getText());
                pst.setString(7,value3);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
            }
            catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            finally {
                try{
                    rs.close();
                    pst.close();
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_save_butActionPerformed

    private void calc_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_butActionPerformed
        // TODO add your handling code here:
        int salary = Integer.parseInt(txt_sal.getText());
        if(r_percentage.isSelected()== true){
            int percentage = Integer.parseInt(txt_percentage.getText());
            //calculate the total hours of overtime
            int total_percentage_deduction = salary /100 * percentage;
            String x = String.valueOf(total_percentage_deduction);
            int sal = salary - total_percentage_deduction;
            lbl_total.setText(x);
            lbl_sal.setText(String.valueOf(sal));
        }
        if(r_amount.isSelected()== true){
            int deduction = Integer.parseInt(txt_deduction.getText());
            //calculate the total hours of overtime
            int total_amount_deduction =  salary - deduction;
            String s = String.valueOf(total_amount_deduction);
            lbl_sal.setText(s);
            lbl_total.setText(String.valueOf(deduction));
        }
    }//GEN-LAST:event_calc_butActionPerformed

    private void clear_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_butActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_dob.setText("");
        txt_grade.setText("");
        txt_doj.setText("");
        txt_desig.setText("");
        txt_doj.setText("");
        lbl_total.setText("0.00");
        txt_percentage.setText("");
        txt_deduction.setText("");
        txt_reason.setText("");
        txt_search.setText("");
        lbl_sal.setText("0.00");
    }//GEN-LAST:event_clear_butActionPerformed

    private void search_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="select *from employee where Employee_ID=? ";
            pst=con.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
            String add1 =rs.getString("Employee_ID");
            txt_id.setText(add1);
            String add2 =rs.getString("First_Name");
            txt_firstname.setText(add2);
            String add3 =rs.getString("Last_Name");
            txt_surname.setText(add3);
            String add4 =rs.getString("DateOfBirth");
            txt_dob.setText(add4);
            String add7 =rs.getString("Salary");
            txt_sal.setText(add7);
            String add8 =rs.getString("Grade");
            txt_grade.setText(add8);
            String add9 =rs.getString("Hire_Date");
            txt_doj.setText(add9);
            String add17 =rs.getString("Designation");
            txt_desig.setText(add17);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {
            try{
                rs.close();
                pst.close();
            }
            catch(SQLException e){
            }
        }
    }//GEN-LAST:event_search_butActionPerformed

    private void txt_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_percentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_percentageActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        MenuAdmin me = new MenuAdmin();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButActionPerformed

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
        LogIn x = new LogIn();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deduction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new deduction().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel background;
    private javax.swing.JButton calc_but;
    private javax.swing.JButton clear_but;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_sal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JButton logout_but;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JButton save_but;
    private javax.swing.JButton search_but;
    private javax.swing.JTextField txt_deduction;
    private javax.swing.JLabel txt_desig;
    private javax.swing.JLabel txt_dob;
    private javax.swing.JLabel txt_doj;
    private javax.swing.JLabel txt_firstname;
    private javax.swing.JLabel txt_grade;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_reason;
    private javax.swing.JLabel txt_sal;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_surname;
    // End of variables declaration//GEN-END:variables
}
