/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vedant
 */
public class OwnDetails extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form NewJFrame
     */
    public OwnDetails() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        con = con_class.java_con();
        lbl_emp.setText(String.valueOf(Emp.empID));
        selfDet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();
        txt_gender = new javax.swing.JLabel();
        txt_fname = new javax.swing.JLabel();
        txt_grade = new javax.swing.JLabel();
        txt_post = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();
        txt_sal = new javax.swing.JLabel();
        txt_lname = new javax.swing.JLabel();
        txt_mname = new javax.swing.JLabel();
        txt_cont = new javax.swing.JLabel();
        txt_doj = new javax.swing.JLabel();
        txt_dob = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Grade");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 250, 38, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 50, 80, 30);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hire Date");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 217, 61, 30);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 170, 49, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 90, 30);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salary");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 207, 40, 30);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 170, 35, 30);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Designation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 250, 76, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 127, 82, 30);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 87, 47, 30);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(100, 0, 50, 30);

        BackBut.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 153, 152));
        BackBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut);
        BackBut.setBounds(490, 0, 50, 40);

        txt_gender.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_gender.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_gender);
        txt_gender.setBounds(120, 90, 110, 30);

        txt_fname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_fname);
        txt_fname.setBounds(120, 50, 110, 30);

        txt_grade.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_grade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_grade);
        txt_grade.setBounds(120, 250, 110, 30);

        txt_post.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_post.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_post);
        txt_post.setBounds(370, 250, 150, 30);

        txt_email.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_email);
        txt_email.setBounds(370, 170, 150, 30);

        txt_sal.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_sal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_sal);
        txt_sal.setBounds(370, 210, 150, 30);

        txt_lname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_lname);
        txt_lname.setBounds(330, 50, 110, 30);

        txt_mname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_mname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_mname);
        txt_mname.setBounds(230, 50, 100, 30);

        txt_cont.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_cont.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_cont);
        txt_cont.setBounds(120, 170, 110, 30);

        txt_doj.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_doj.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_doj);
        txt_doj.setBounds(120, 210, 110, 30);

        txt_dob.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_dob);
        txt_dob.setBounds(120, 130, 110, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 40, 530, 20);

        Background.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(561, 346));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackButActionPerformed

    public void selfDet(){
        try{
            String id = lbl_emp.getText().toString();
            String sql ="select First_Name,Middle_Name,Last_Name,DateOfBirth,Gender,Salary,Grade,Contact,Hire_Date,Designation,Email from employee where Employee_ID=? ";

            pst=con.prepareStatement(sql);
            pst.setString(1,id);
            rs=pst.executeQuery();
            if(rs.next()){
                                
                String add1 =rs.getString("First_Name");
                txt_fname.setText(add1);
                
                String add2 =rs.getString("Middle_Name");
                txt_mname.setText(add2);

                String add3 =rs.getString("Last_Name");
                txt_lname.setText(add3);

                String add4 =rs.getString("DateOfBirth");
                txt_dob.setText(add4);

                String add5 =rs.getString("Salary");
                txt_sal.setText(add5);

                String add6 =rs.getString("Grade");
                txt_grade.setText(add6);
                
                String add7 =rs.getString("Gender");
                txt_gender.setText(add7);
                
                String add8 =rs.getString("Hire_Date");
                txt_doj.setText(add8);
                
                String add9 =rs.getString("Designation");
                txt_post.setText(add9);
               
                String add10 =rs.getString("Email");
                txt_email.setText(add10);
               
                String add11 =rs.getString("Contact");
                txt_cont.setText(add11);
                
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OwnDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel txt_cont;
    private javax.swing.JLabel txt_dob;
    private javax.swing.JLabel txt_doj;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_fname;
    private javax.swing.JLabel txt_gender;
    private javax.swing.JLabel txt_grade;
    private javax.swing.JLabel txt_lname;
    private javax.swing.JLabel txt_mname;
    private javax.swing.JLabel txt_post;
    private javax.swing.JLabel txt_sal;
    // End of variables declaration//GEN-END:variables
}
