/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vedant
 */
public class passupdate extends javax.swing.JFrame {
    Connection con= null;
    PreparedStatement insert = null;
    ResultSet rs=null;  

    /**
     * Creates new form passupdate
     */
    public passupdate() {
        initComponents();
         con = con_class.java_con();
         lbl_emp.setText(String.valueOf(Emp.empID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_oldpass = new javax.swing.JPasswordField();
        txt_newpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txt_conpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        change_but = new javax.swing.JButton();
        lbl_emp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logout_but = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Old Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 120, 72, 24);

        txt_oldpass.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_oldpassActionPerformed(evt);
            }
        });
        getContentPane().add(txt_oldpass);
        txt_oldpass.setBounds(200, 120, 190, 31);

        txt_newpass.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newpassActionPerformed(evt);
            }
        });
        getContentPane().add(txt_newpass);
        txt_newpass.setBounds(200, 170, 190, 28);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 170, 87, 28);

        txt_conpass.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conpassActionPerformed(evt);
            }
        });
        txt_conpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_conpassKeyReleased(evt);
            }
        });
        getContentPane().add(txt_conpass);
        txt_conpass.setBounds(200, 220, 190, 28);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 220, 110, 28);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(108, 60, 0, 0);

        change_but.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        change_but.setForeground(new java.awt.Color(0, 57, 124));
        change_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/replace.png"))); // NOI18N
        change_but.setText("Change");
        change_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_butActionPerformed(evt);
            }
        });
        getContentPane().add(change_but);
        change_but.setBounds(200, 280, 120, 39);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(120, 0, 60, 30);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logged in as : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 93, 30);

        logout_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        logout_but.setForeground(new java.awt.Color(0, 152, 153));
        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logout_but.setFocusTraversalPolicyProvider(true);
        logout_but.setHideActionText(true);
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        getContentPane().add(logout_but);
        logout_but.setBounds(530, 0, 50, 40);

        BackBut.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 153, 152));
        BackBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut);
        BackBut.setBounds(480, 0, 50, 40);

        background.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 770);

        setSize(new java.awt.Dimension(601, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newpassActionPerformed

    private void txt_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conpassActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_txt_conpassActionPerformed

    private void change_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_butActionPerformed
        // TODO add your handling code here:
        
        String oldpass = txt_oldpass.getText();
        String newpass = txt_newpass.getText();
        String conpass = txt_conpass.getText();
        String empid = lbl_emp.getText(); 
        System.out.println("oldpassword"+oldpass);
        System.out.println("new password: "+newpass);
        System.out.println("Confirm text field : "+conpass);
        System.out.println("lable id : "+empid);
        
        String sql = "select * from login where UserID = ? ";  
        try {
            insert = con.prepareStatement(sql);
            insert.setString(1, empid);
            rs=insert.executeQuery();
            if(rs.next()){
                String orpass = rs.getString(2);
                System.out.println("Original:"+orpass);
                if(oldpass == null ? orpass != null : !oldpass.equals(orpass)){
                    JOptionPane.showMessageDialog(this, "Entered old password is incorrect!");
                    System.out.println("Old Password is incorrect!");
                    txt_oldpass.setText("");
                    txt_oldpass.requestFocus();
                }else{
                    if(newpass == null ? conpass != null : !newpass.equals(conpass)){
                        JOptionPane.showMessageDialog(this, "Entered Password Do not Match!");
                        System.out.println("Entered Password Do not Match!");
                        txt_newpass.setText("");
                        txt_conpass.setText("");
                        txt_newpass.requestFocus();
                    }
                    else{
                        System.out.println("Everything is correct!");
                        int dialogResult;
                        dialogResult = JOptionPane.showConfirmDialog(null,"Are you sure you want to change your password?","Warning",JOptionPane.YES_NO_OPTION);
                        if(dialogResult == JOptionPane.YES_OPTION){
                            String updsql = "update login set Password = ? where UserID = ?";  
                            insert = con.prepareStatement(updsql);
                            insert.setString(1, newpass);
                            insert.setString(2, empid);
                            insert.execute();
                            JOptionPane.showMessageDialog(this, "Password Updated Successully!");
                            LogIn x = new LogIn();
                            x.setVisible(true);
                            this.dispose();
                        }
                    }
                }
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(passupdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_change_butActionPerformed

    private void txt_conpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_conpassKeyReleased
        // TODO add your handling code here:  
    }//GEN-LAST:event_txt_conpassKeyReleased

    private void txt_oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_oldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_oldpassActionPerformed

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
        LogIn x = new LogIn();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_butActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        String div = null;
        String empid = lbl_emp.getText();
        String sql = "select * from login where UserID = ?";
         try {
            insert = con.prepareStatement(sql);
            insert.setString(1, empid);
            rs=insert.executeQuery();
            if(rs.next()){
                div = rs.getString(3);
                if("Admin".equals(div))
                {
                    MenuAdmin me = new MenuAdmin();
                    me.setVisible(true);
                    this.dispose();
                }
                if("Employee".equals(div)){
                    MenuEmp me = new MenuEmp();
                    me.setVisible(true);
                    this.dispose();
                }
            }
         } catch (SQLException ex) {
            Logger.getLogger(passupdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_BackButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new passupdate().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel background;
    private javax.swing.JButton change_but;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JButton logout_but;
    private javax.swing.JPasswordField txt_conpass;
    private javax.swing.JPasswordField txt_newpass;
    private javax.swing.JPasswordField txt_oldpass;
    // End of variables declaration//GEN-END:variables
}
