/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MasterKhan
 */
public class Payslip extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Payslip
     */
    public Payslip() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        lbl_emp.setText(String.valueOf(Emp.empID)); 
         conn = con_class.java_con();
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();
        logout_but = new javax.swing.JButton();
        txt_ID = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JLabel();
        txt_surname = new javax.swing.JLabel();
        txt_dob = new javax.swing.JLabel();
        txt_salary = new javax.swing.JLabel();
        txt_doj = new javax.swing.JLabel();
        txt_grade = new javax.swing.JLabel();
        txt_designation = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 80, 20);

        txt_search.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(207, 44, 520, 30);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Employee ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 115, 78, 20);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("First Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 165, 78, 20);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Last Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 215, 78, 20);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Date Of Birth:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 270, 72, 20);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Designation:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 120, 66, 15);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Grade:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 160, 71, 30);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Date Hired:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 220, 71, 15);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Salary:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 260, 71, 20);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 57, 124));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment.png"))); // NOI18N
        jButton1.setText("Initiate Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 330, 230, 40);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logged in as : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 93, 30);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(120, 0, 60, 30);

        BackBut.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 153, 152));
        BackBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut);
        BackBut.setBounds(770, 0, 50, 40);

        logout_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        logout_but.setForeground(new java.awt.Color(0, 152, 153));
        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logout_but.setFocusTraversalPolicyProvider(true);
        logout_but.setHideActionText(true);
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        getContentPane().add(logout_but);
        logout_but.setBounds(820, 0, 50, 40);

        txt_ID.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_ID);
        txt_ID.setBounds(200, 110, 170, 30);

        txt_firstname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(200, 160, 170, 30);

        txt_surname.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_surname);
        txt_surname.setBounds(200, 210, 170, 30);

        txt_dob.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_dob.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_dob);
        txt_dob.setBounds(200, 260, 170, 30);

        txt_salary.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_salary);
        txt_salary.setBounds(580, 260, 170, 30);

        txt_doj.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_doj.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_doj);
        txt_doj.setBounds(580, 210, 170, 30);

        txt_grade.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_grade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_grade);
        txt_grade.setBounds(580, 160, 170, 30);

        txt_designation.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_designation.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_designation);
        txt_designation.setBounds(580, 110, 170, 30);

        Background.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(887, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void payment(String emp,float amt){
        String adm = lbl_emp.getText();
        try {
            pst = conn.prepareStatement("insert into payments(Payed_To,Amount,Payed_By) values(?,?,?)");
            pst.setString(1, emp);
            pst.setFloat(2, amt);
            pst.setString(3, adm);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Payment Successfull!");
            JOptionPane.showMessageDialog(null,"Report was successfully generated!");
        } catch (SQLException ex) {
            Logger.getLogger(Payslip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String value = txt_firstname.getText();
            String value0 = txt_surname.getText();
            String value1 = txt_ID.getText();
            String value2 = txt_designation.getText();
          //String value3 = txt_designation.getText();
                                                      
            
            JFileChooser dialog = new JFileChooser();
            dialog.setSelectedFile(new File(value +" "+ value0+"-Salary Slip"+".pdf"));
            int dialogResult = dialog.showSaveDialog(null);
            if (dialogResult==JFileChooser.APPROVE_OPTION){
            String filePath = dialog.getSelectedFile().getPath();
           
        try {
            // TODO add your handling code here:
            String val=null;
            String reason =null;
            int calcTotal = 0;
            float x = 0;
            String t2 =null;
            String t3 =null;
            String t4 =null;
            String t5 =null;
            String t9 =null;
            String sql ="select * from deductions where Employee_ID = '"+value1+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                 val = rs.getString(6);
                reason = rs.getString(7);
            }
            System.out.println(val);
            
            String sq ="select * from allowance where Employee_ID = '"+value1+"'";
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery(); 
               
            while(rs.next()){
                calcTotal = Integer.parseInt(txt_salary.getText());
                t2 =rs.getString(2);
                t3 =rs.getString(3);
                t4 =rs.getString(4);
                t5 =rs.getString(5);
                t9 =rs.getString(9);
                x = Float.valueOf(rs.getString(9));
            }
           int v = Integer.parseInt(val);
           float total = calcTotal+ x-v;
           Document myDocument = new Document();
           PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
           myDocument.open();
           
           myDocument.add(new Paragraph("PAY SLIP",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD )));
           myDocument.add(new Paragraph(new Date().toString()));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add((new Paragraph("EMPLOYEE DETAILS",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD))));
           myDocument.add((new Paragraph("Name of Employee: " +value + " "+value0,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
           myDocument.add((new Paragraph("Designation: "+value2,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN))));
           
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("SALARY",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Basic Salary: Rs."+calcTotal,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Overtime: "+t2+" Hours",FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Medical: Rs." +t3,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Bonus: Rs."+t4,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Other: Rs."+t5,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Total Allowance: Rs."+t9,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("DEDUCTION",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Deduction Details: "+reason,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("Total Deductions : Rs."+val ,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           myDocument.add(new Paragraph("TOTAL PAYMENT",FontFactory.getFont(FontFactory.TIMES_ROMAN,15,Font.BOLD)));
           myDocument.add(new Paragraph("Net Pay : Rs." +total,FontFactory.getFont(FontFactory.TIMES_ROMAN,10,Font.PLAIN)));
           myDocument.add(new Paragraph("-------------------------------------------------------------------------------------------"));
           
           myDocument.newPage();
           myDocument.close();  
           payment(value1,total);   
     }
        catch(DocumentException | HeadlessException | FileNotFoundException | NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
         
         
     }
     finally {
            
            try{
               rs.close();
               pst.close();
                
            }
            catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
         
            }
     }
   }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{
           
            String sql ="select * from employee where Employee_ID=?";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();

            if(rs.next()){
                String add1 =rs.getString("Employee_ID");
                txt_ID.setText(add1);

                String add2 =rs.getString("First_Name");
                txt_firstname.setText(add2);

                String add3 =rs.getString("Last_Name");
                txt_surname.setText(add3);

                String add4 =rs.getString("DateOfBirth");
                txt_dob.setText(add4);

                String add5 =rs.getString("Designation");
                txt_designation.setText(add5);

                String add7 =rs.getString("Salary");
                txt_salary.setText(add7);

                String add8 =rs.getString("Hire_Date");
                txt_doj.setText(add8);

                String add9 =rs.getString("Grade");
                txt_grade.setText(add9);

            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        MenuAdmin me = new MenuAdmin();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButActionPerformed

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
        LogIn x = new LogIn();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payslip().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JButton logout_but;
    private javax.swing.JLabel txt_ID;
    private javax.swing.JLabel txt_designation;
    private javax.swing.JLabel txt_dob;
    private javax.swing.JLabel txt_doj;
    private javax.swing.JLabel txt_firstname;
    private javax.swing.JLabel txt_grade;
    private javax.swing.JLabel txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_surname;
    // End of variables declaration//GEN-END:variables
}
