/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRoll;

import static PayRoll.Add_Admin.isContactValid;
import static PayRoll.Add_Admin.isEmailValid;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Vedant
 */
public class UpdateEmp extends javax.swing.JFrame {
    Connection con= null;
    PreparedStatement pst = null;
    ResultSet rs=null;

    /**
     * Creates new form AddEmp
     */
    public UpdateEmp() {
        initComponents();
        con = con_class.java_con();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        lbl_emp.setText(String.valueOf(Emp.empID));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_hdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_post = new javax.swing.JTextField();
        txt_cont = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        savebut = new javax.swing.JButton();
        delete_But = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_grade = new javax.swing.JTextField();
        txt_sal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Resetbut1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        update_BUt = new javax.swing.JButton();
        txt_mname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rd_male = new javax.swing.JRadioButton();
        rd_female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        BackBut = new javax.swing.JButton();
        logout_but = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 80, 30);
        getContentPane().add(txt_id);
        txt_id.setBounds(140, 180, 150, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last  Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 220, 70, 30);
        getContentPane().add(txt_fname);
        txt_fname.setBounds(140, 220, 150, 30);
        getContentPane().add(txt_hdate);
        txt_hdate.setBounds(140, 420, 150, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HireDate");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 420, 60, 30);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Designation");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 380, 70, 30);
        getContentPane().add(txt_post);
        txt_post.setBounds(420, 380, 160, 30);
        getContentPane().add(txt_cont);
        txt_cont.setBounds(140, 340, 150, 30);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 340, 60, 30);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add Details of the employee here.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 150, 210, 16);

        savebut.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        savebut.setForeground(new java.awt.Color(0, 153, 152));
        savebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add user.png"))); // NOI18N
        savebut.setText("Add");
        savebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebutActionPerformed(evt);
            }
        });
        getContentPane().add(savebut);
        savebut.setBounds(140, 490, 110, 30);

        delete_But.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        delete_But.setForeground(new java.awt.Color(0, 153, 152));
        delete_But.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        delete_But.setText("Delete");
        delete_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ButActionPerformed(evt);
            }
        });
        getContentPane().add(delete_But);
        delete_But.setBounds(460, 490, 110, 30);

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("First Name");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 220, 70, 30);
        getContentPane().add(txt_lname);
        txt_lname.setBounds(420, 220, 160, 30);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 340, 50, 30);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 296, 50, 30);

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date Of Birth");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 260, 80, 30);

        txt_dob.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txt_dob);
        txt_dob.setBounds(140, 260, 150, 30);

        txt_email.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txt_email);
        txt_email.setBounds(420, 340, 160, 30);

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Grade");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 380, 35, 30);

        txt_grade.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        getContentPane().add(txt_grade);
        txt_grade.setBounds(140, 380, 150, 30);
        getContentPane().add(txt_sal);
        txt_sal.setBounds(420, 420, 160, 30);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salary");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 416, 38, 30);

        Resetbut1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Resetbut1.setForeground(new java.awt.Color(0, 153, 152));
        Resetbut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Clear.png"))); // NOI18N
        Resetbut1.setText("Clear");
        Resetbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resetbut1ActionPerformed(evt);
            }
        });
        getContentPane().add(Resetbut1);
        Resetbut1.setBounds(620, 490, 110, 30);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 80, 80, 30);

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });
        getContentPane().add(txt_search);
        txt_search.setBounds(140, 80, 440, 30);

        update_BUt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        update_BUt.setForeground(new java.awt.Color(0, 153, 152));
        update_BUt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update.png"))); // NOI18N
        update_BUt.setText("Update");
        update_BUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_BUtActionPerformed(evt);
            }
        });
        getContentPane().add(update_BUt);
        update_BUt.setBounds(300, 490, 110, 30);
        getContentPane().add(txt_mname);
        txt_mname.setBounds(420, 260, 160, 30);

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Middle Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 260, 80, 30);

        rd_male.setBackground(new java.awt.Color(30, 99, 120));
        rd_male.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        rd_male.setForeground(new java.awt.Color(204, 204, 255));
        rd_male.setText("Male");
        rd_male.setContentAreaFilled(false);
        rd_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_maleActionPerformed(evt);
            }
        });
        getContentPane().add(rd_male);
        rd_male.setBounds(140, 300, 70, 23);

        rd_female.setBackground(new java.awt.Color(0, 75, 97));
        rd_female.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        rd_female.setForeground(new java.awt.Color(204, 204, 255));
        rd_female.setText("Female");
        rd_female.setContentAreaFilled(false);
        getContentPane().add(rd_female);
        rd_female.setBounds(200, 300, 80, 23);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logged in as : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 93, 30);

        lbl_emp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lbl_emp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_emp.setText("ID");
        getContentPane().add(lbl_emp);
        lbl_emp.setBounds(120, 0, 60, 30);

        BackBut.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 153, 152));
        BackBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut);
        BackBut.setBounds(710, 0, 50, 40);

        logout_but.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        logout_but.setForeground(new java.awt.Color(0, 152, 153));
        logout_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logout_but.setFocusTraversalPolicyProvider(true);
        logout_but.setHideActionText(true);
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        getContentPane().add(logout_but);
        logout_but.setBounds(760, 0, 50, 40);

        background.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1366, 770);

        setSize(new java.awt.Dimension(826, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isEmailValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    } 
    
    public static boolean isContactValid(String s) 
    { 
        // The given argument to compile() method  
        // is regular expression. With the help of  
        // regular expression we can validate mobile 
        // number.  
        // 1) Begins with 0 or 91 
        // 2) Then contains 7 or 8 or 9. 
        // 3) Then contains 9 digits 
       Pattern p = Pattern.compile("(0/91)?[7-9][0-9]{9}");
       //  Pattern p = Pattern.compile("[0-9]{10}");
  
        // Pattern class contains matcher() method 
        // to find matching between given number  
        // and regular expression 
        Matcher m = p.matcher(s); 
        return (m.find() && m.group().equals(s)); 
    } 
    
    
    private void savebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebutActionPerformed
        // TODO add your handling code here:
        String gender=null;
        if(rd_male.isSelected())
            gender="Male";
        if(rd_female.isSelected())
            gender="Female";
           String email = txt_email.getText();
           String mobile = txt_cont.getText();
        if((!isEmailValid(email))||(!isContactValid(mobile))){
              
               if(!isContactValid(mobile)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Contact Number!");
                   txt_cont.setText("");
               }
               if(!isEmailValid(email)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Email Address!");
                   txt_email.setText("");
               }
        }
        else{
            try {
                String sql ="insert into employee " 
                            + "(Employee_ID,First_Name,Middle_Name,Last_Name,"
                            + "Gender,DateOfBirth,Email,"
                            + "Contact,Hire_Date,Designation,Grade,Salary,AddedBy)"
                            + " values (?,?,?,?,?,?,?,?,?,?,?,?,?) ";

                pst=con.prepareStatement(sql);
                pst.setString(1,txt_id.getText());
                pst.setString(2,txt_fname.getText());
                pst.setString(3,txt_mname.getText());
                pst.setString(4,txt_lname.getText());
                pst.setString(5,gender);
                pst.setString(6,txt_dob.getText());
                pst.setString(7,email);
                pst.setString(8,mobile);
                pst.setString(9,txt_hdate.getText());
                pst.setString(10,txt_post.getText());
                pst.setString(11, txt_grade.getText());
                pst.setString(12, txt_sal.getText());
                pst.setString(13, lbl_emp.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

                txt_id.setText("");
                txt_fname.setText("");
                txt_mname.setText("");
                txt_lname.setText("");
                txt_dob.setText("");
                txt_email.setText("");
                txt_cont.setText("");
                txt_post.setText("");
                txt_grade.setText("");
                txt_hdate.setText("");
                txt_sal.setText("");
                txt_search.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(UpdateEmp.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
            
    }//GEN-LAST:event_savebutActionPerformed

    private void delete_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ButActionPerformed
        // TODO add your handling code here:
        String id=txt_id.getText();
            try{
                String sql ="delete from employee where Employee_ID=? ";
                pst=con.prepareStatement(sql);
                pst.setString(1, id);
                pst.execute();
                
                String sql1 ="call del_login(?) ";
                pst=con.prepareStatement(sql1);
                pst.setString(1, id);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(HeadlessException | SQLException e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
            }
            
            txt_id.setText("");
            txt_fname.setText("");
            txt_mname.setText("");
            txt_lname.setText("");
            txt_dob.setText("");
            txt_email.setText("");
            txt_cont.setText("");
            txt_post.setText("");
            txt_grade.setText("");
            txt_hdate.setText("");
            txt_sal.setText("");
            txt_search.setText("");
    }//GEN-LAST:event_delete_ButActionPerformed

    private void Resetbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resetbut1ActionPerformed
        // TODO add your handling code here:
        
            txt_id.setText("");
            txt_fname.setText("");
            txt_mname.setText("");
            txt_lname.setText("");
            txt_dob.setText("");
            txt_email.setText("");
            txt_cont.setText("");
            txt_post.setText("");
            txt_grade.setText("");
            txt_hdate.setText("");
            txt_sal.setText("");
            txt_search.setText("");
    }//GEN-LAST:event_Resetbut1ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyPressed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        // TODO add your handling code here:
        
        try{

            String sql ="select First_Name,Middle_Name,Last_Name,DateOfBirth,Gender,Salary,Grade,Contact,Hire_Date,Designation,Email from employee where Employee_ID=? ";

            pst=con.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
                String value1 = txt_search.getText();
                txt_id.setText(value1);
                
                String add1 =rs.getString("First_Name");
                txt_fname.setText(add1);
                
                String add2 =rs.getString("Middle_Name");
                txt_mname.setText(add2);

                String add3 =rs.getString("Last_Name");
                txt_lname.setText(add3);

                String add4 =rs.getString("DateOfBirth");
                txt_dob.setText(add4);

                String add5 =rs.getString("Salary");
                txt_sal.setText(add5);

                String add6 =rs.getString("Grade");
                txt_grade.setText(add6);
                
                String add7 =rs.getString("Gender");
                if("Male".equals(add7))
                    rd_male.setSelected(true);
                if("Female".equals(add7))
                    rd_female.setSelected(true);
                
                
                String add8 =rs.getString("Hire_Date");
                txt_hdate.setText(add8);
                
                String add9 =rs.getString("Designation");
                txt_post.setText(add9);
               
                String add10 =rs.getString("Email");
                txt_email.setText(add10);
               
                String add11 =rs.getString("Contact");
                txt_cont.setText(add11);
                
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }
        }

    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_searchKeyTyped

    private void update_BUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_BUtActionPerformed
        // TODO add your handling code here:
        String id = txt_search.getText();
        String value1 = txt_cont.getText();
        String value2 = txt_email.getText();
        String value3 = txt_post.getText();
        String value4 = txt_grade.getText();
        String value5 = txt_sal.getText();
        
        if((!isEmailValid(value2))||(!isContactValid(value1))||((!rd_male.isSelected())&&(!rd_female.isSelected()))){
               if((!rd_male.isSelected())&&(!rd_female.isSelected())){
                   JOptionPane.showMessageDialog(null, "Please Select the gender by clicking on the respective button(Male / Female)!");
               }
               if(!isContactValid(value1)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Contact Number!");
                   txt_cont.setText("");
               }
               if(!isEmailValid(value2)){
                   JOptionPane.showMessageDialog(null, "Enter a valid Email Address!");
                   txt_email.setText("");
               }
        }
        else{
            try{ 
                pst = con.prepareStatement("update employee set Contact=?,Email=?,Designation=?, Grade=?, Salary=? where Employee_ID=?");           
                pst.setString(1, value1);
                pst.setString(2, value2);
                pst.setString(3, value3);
                pst.setString(4, value4);
                pst.setString(5, value5);
                pst.setString(6, id);
                pst.executeUpdate();  
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }finally {
                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }              
    }//GEN-LAST:event_update_BUtActionPerformed

    private void rd_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_maleActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        MenuAdmin me = new MenuAdmin();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButActionPerformed

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        // TODO add your handling code here:
        LogIn x = new LogIn();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UpdateEmp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton Resetbut1;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete_But;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JButton logout_but;
    private javax.swing.JRadioButton rd_female;
    private javax.swing.JRadioButton rd_male;
    private javax.swing.JButton savebut;
    private javax.swing.JTextField txt_cont;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_grade;
    private javax.swing.JTextField txt_hdate;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextField txt_post;
    private javax.swing.JTextField txt_sal;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update_BUt;
    // End of variables declaration//GEN-END:variables
}
